// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKOvcPc5FuPuS-769Mn_L53Mk4BmxXZ6s',
    appId: '1:815419857591:web:13992a55c9a6d57cba0b32',
    messagingSenderId: '815419857591',
    projectId: 'marinobarbersalon-5b1aa',
    authDomain: 'marinobarbersalon-5b1aa.firebaseapp.com',
    storageBucket: 'marinobarbersalon-5b1aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAleJD9s7e-JBo9A73rS6Rrh3lujcfu61w',
    appId: '1:815419857591:android:732a403565395b85ba0b32',
    messagingSenderId: '815419857591',
    projectId: 'marinobarbersalon-5b1aa',
    storageBucket: 'marinobarbersalon-5b1aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXXzXIpPe-KRwr0LR7Yo5HFcx-AllKx8',
    appId: '1:815419857591:ios:c4d0a7f4c5e94ecbba0b32',
    messagingSenderId: '815419857591',
    projectId: 'marinobarbersalon-5b1aa',
    storageBucket: 'marinobarbersalon-5b1aa.firebasestorage.app',
    iosBundleId: 'com.example.marinoBarberSalonFlutter',
  );
}
